version: "2"

services:

######################### SETUP OF PROXY AND SSL ###############################

# Don't edit this service
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

# Don't edit this service
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    depends_on:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

# Don't edit this service
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
      - nginx-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

####################### SETUP OF DOCKER CONTAINERS #############################

# Spin up Rstudio docker

## Use this version to add several users
  # rstudio:
  #   restart: always
  #   build: ./addusers
  #   container_name: rstudio
  #   depends_on:
  #     - shiny
  #   expose:
  #     - "8787"
  #   environment:
  #     - VIRTUAL_HOST=rstudio.mydomain.com # change line
  #     - VIRTUAL_NETWORK=nginx-proxy
  #     - VIRTUAL_PORT=80
  #     - LETSENCRYPT_HOST=rstudio.mydomain.com # change line
  #     - LETSENCRYPT_EMAIL=me@myemail.com # change line
  #   volumes:
  #     - shiny-apps:/home/apps
  #     - r-packages:/usr/local/lib/R/site-library

  rstudio:
    restart: always
    image: rocker/rstudio
    container_name: rstudio
    expose:
      - "8787"
    environment:
      - VIRTUAL_HOST=rstudio.medialytic.io # change line
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=rstudio.medialytic.io # change line
      - LETSENCRYPT_EMAIL=info@medialytic.io # change line
      - USER=RUSER # Set running: docker-compose run -e RUSER='your username'
      - PASSWORD=RPASSWORD # Set running: docker-compose run -e RPASSWORD='your password'
    volumes:
      - r-packages:/usr/local/lib/R/site-library
      - backup:/home/


# Create data docker volumes
volumes:
  r-packages: # holds new common libraries
  backup: # makes backup of the /home folder in Rstudio docker
